org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Opt out of AGP 9 breaking DSL changes
android.newDsl=false

# Suppress AAR metadata checks across mismatched plugin compileSdk versions
android.dependency.suppressUnsupportedCompileSdk=36
